openapi: 3.0.0
info:
  title: wa48
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /user:
    get:
      summary: get all
      tags:
        - user
      responses: {}
      operationId: get-user
components:
  schemas: {}
